AAB Build Android AAB

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle wrapper
      run: |
        echo "Setting up Gradle wrapper..."
        mkdir -p gradle/wrapper
        curl -L -o gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/master/gradle/wrapper/gradle-wrapper.jar
        
        if [ ! -f gradle/wrapper/gradle-wrapper.properties ]; then
          cat > gradle/wrapper/gradle-wrapper.properties << EOL
        distributionBase=GRADLE_USER_HOME
        distributionPath=wrapper/dists
        distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-bin.zip
        zipStoreBase=GRADLE_USER_HOME
        zipStorePath=wrapper/dists
        EOL
        fi
        
        chmod +x gradlew
        echo "Gradle wrapper setup complete!"

    - name: Build Debug AAB
      run: |
        echo "Building Android App Bundle..."
        ./gradlew bundleDebug --stacktrace
        
    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: zenfit-ai-debug-aab
        path: app/build/outputs/bundle/debug/app-debug.aab
        retention-days: 30
        
    - name: Build Summary
      run: |
        echo "✅ Build completed successfully!"
        echo "📱 AAB file location: app/build/outputs/bundle/debug/app-debug.aab"
        echo "📥 Download from the 'Artifacts' section above"
        echo "🚀 Ready for Google Play Store upload!"
